title: Title of your CV site
profile_img: /assets/img/profile.webp
icon_img: /assets/img/icon.webp

name: "Peyton Blanchard"
job: "〈MSU Student〉"

phone_number: 248-444-0605
address: Brighton, Michigan
email: blanc142@msu.edu
linkedin_username: Peyton Blanchard
github_username: peytxn
instagram_username: peytxn.blanchard
twitter_username: peytxn_
facebook_username: Peyton Blanchard
youtube_username: peytxn
blog_url: peytxn.github.io

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /resume
baseurl:

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag